# Generated by Django 3.2.16 on 2022-11-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernamee', models.CharField(max_length=40)),
                ('passwordd', models.CharField(max_length=1000)),
            ],
        ),
    ]
