# Generated by Django 3.2.16 on 2022-11-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employeeapp_', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Logins',
        ),
        migrations.RenameField(
            model_name='logins',
            old_name='passwordd',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='logins',
            old_name='usernamee',
            new_name='username',
        ),
    ]
