# Generated by Django 3.2.16 on 2022-11-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employeeapp_', '0005_appraisal'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='Department',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='Name',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
