# Generated by Django 3.2.16 on 2022-11-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employeeapp_', '0006_auto_20221105_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='feedback',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='hikegot',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='performance',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='progress',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='salary',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
