# Generated by Django 3.2.16 on 2022-11-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employeeapp_', '0007_auto_20221105_1902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appraisal',
            new_name='Appraisals',
        ),
    ]
