# Generated by Django 3.2.16 on 2022-11-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employeeapp_', '0008_rename_appraisal_appraisals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmoloyeeName', models.CharField(blank=True, max_length=35, null=True)),
                ('task', models.CharField(blank=True, max_length=35, null=True)),
                ('date', models.DateField(blank=True, max_length=35, null=True)),
                ('timeIn', models.TimeField(blank=True, max_length=35, null=True)),
                ('timeOut', models.TimeField(blank=True, max_length=35, null=True)),
                ('efforts', models.DurationField()),
            ],
        ),
    ]
