# Generated by Django 3.2.16 on 2022-11-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employeeapp_', '0009_timesheets'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheets',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
