# Generated by Django 3.2.16 on 2022-11-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employeeapp_', '0011_rename_city_employe_employeeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='id',
        ),
        migrations.AlterField(
            model_name='employe',
            name='employeeid',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
