# Generated by Django 3.2.16 on 2022-12-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employeeapp_', '0014_alter_timesheets_efforts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apspraisals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(blank=True, max_length=35, null=True)),
                ('performance', models.CharField(blank=True, max_length=35, null=True)),
            ],
        ),
    ]
